# Generated by Django 5.1.4 on 2025-01-14 13:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('single', 'Single'), ('range', 'Range'), ('set', 'Set')], default='single', max_length=10, verbose_name='Тип генерации')),
                ('result', models.TextField(verbose_name='Результат генерации')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
            ],
        ),
    ]
