# Generated by Django 5.1.4 on 2025-01-14 14:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomnumbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomnumber',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='randomnumber',
            name='mode',
            field=models.CharField(choices=[('single', 'Single'), ('range', 'Range'), ('set', 'Set')], default='single', max_length=10, verbose_name='Тип генерації'),
        ),
        migrations.AlterField(
            model_name='randomnumber',
            name='result',
            field=models.TextField(verbose_name='Результат генерації'),
        ),
    ]
